import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "./component/Layout";
import Modal from "./component/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{background:"#181717"}}>
        <Modal actionLabel="Submit" isOpen={true} title="tedt open"
        />
        <Layout children={children}/>
        </body>
    </html>
  );
}
